name: Verify PR
on:
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - name: Create .env file
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          touch packages/sdk/.env
          echo API_USERNAME=$API_USERNAME > packages/sdk/.env
          echo API_PASSWORD=$API_PASSWORD > packages/sdk/.env
          cat packages/sdk/.env

      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3
