name: Verify PR
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Cache node_modules
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn install

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - name: Create .env file
        run: |
          touch ./shared/sdk/.env
          echo API_USERNAME=${{ secrets.API_USERNAME }} >> ./shared/sdk/.env
          echo API_PASSWORD=${{ secrets.API_PASSWORD }} >> ./shared/sdk/.env

      - run: npx nx format:check
      - run: npx nx affected -t lint,test,build --parallel=3
